ALTER TABLE staff ADD CONSTRAINT fk_staff_address FOREIGN KEY (address_id) REFERENCES ADDRESS (address_id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE staff ADD CONSTRAINT fk_staff_store FOREIGN KEY (store_id) REFERENCES STORE (store_id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE store ADD CONSTRAINT fk_store_staff FOREIGN KEY (manager_staff_id) REFERENCES STAFF (staff_id) ON DELETE NO ACTION ON UPDATE CASCADE;

ALTER SEQUENCE actor_generator RESTART WITH 201;
ALTER SEQUENCE country_generator RESTART WITH 110;
ALTER SEQUENCE city_generator RESTART WITH 601;
ALTER SEQUENCE address_generator RESTART WITH 606;
ALTER SEQUENCE language_generator RESTART WITH 7;
ALTER SEQUENCE category_generator RESTART WITH 17;
ALTER SEQUENCE customer_generator RESTART WITH 600;
ALTER SEQUENCE film_generator RESTART WITH 1001;
ALTER SEQUENCE inventory_generator RESTART WITH 4582;
ALTER SEQUENCE staff_generator RESTART WITH 3;
ALTER SEQUENCE store_generator RESTART WITH 3;
ALTER SEQUENCE payment_generator RESTART WITH 16050;
ALTER SEQUENCE rental_generator RESTART WITH 16050;